backend:
  name: github
  repo: SysSyncAI/enterosgel-ru   # your repo full name
  branch: main

media_folder: "public/uploads"   # files are stored here in repo
public_folder: "/uploads"        # how they are referenced on site

collections:
  - name: "home"
    label: "Homepage Content"
    files:
      - file: "public/cms/home.json"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "string" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - { label: "CTA Label", name: "ctaLabel", widget: "string" }
          - { label: "CTA URL", name: "ctaUrl", widget: "string" }

  - name: "team"
    label: "Team Members"
    folder: "public/cms/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }
