backend:
  name: github
  repo: SysSyncAI/enterosgel-ru   # your GitHub repo
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Homepage Content"
    file: "public/cms/home.json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "team"
    label: "Team Members"
    folder: "public/cms/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }
